/* libgui: text rendering at several sizes, weights and styles.
 *
 * The four faces are generated by libgui/mkfont_user.py from one piece of
 * hand-drawn 8x16 art; see font.h for what they are and mkfont_user.py for
 * how the derived sizes are re-sampled.  This file is the runtime: it
 * unpacks coverage, synthesises bold and italic, and blends glyphs into a
 * 32-bit surface.
 *
 * Everything here is integer arithmetic and bounded loops -- no libc, no
 * allocation, no floating point, no recursion -- so it costs nothing to
 * call from an interrupt-free freestanding program and can be compiled
 * for the host and tested directly (tools/test_font.c).
 */

#include "font.h"

#define GLYPH_FIRST 0x20
#define GLYPH_LAST  0x7E
#define GLYPH_COUNT 95          /* plus one fallback cell at index 95 */
#define GLYPH_CELLS (GLYPH_COUNT + 1)

/* The tables are generated, their sizes are declared by hand in font.h,
 * and a mismatch would be read past the end of an array rather than
 * diagnosed.  Make it a compile error instead: these declare an array of
 * length -1 the moment a face changes shape without the header
 * following it. */
#define FONT_ASSERT(name, cond) \
    typedef char font_assert_##name[(cond) ? 1 : -1]

FONT_ASSERT(cov6x12, sizeof gui_font_cov6x12 == GLYPH_CELLS * 6 * 12 / 2);
FONT_ASSERT(cov12x24, sizeof gui_font_cov12x24 == GLYPH_CELLS * 12 * 24 / 2);
FONT_ASSERT(cov16x32, sizeof gui_font_cov16x32 == GLYPH_CELLS * 16 * 32 / 2);
FONT_ASSERT(bits8x16, sizeof gui_font8x16 == GLYPH_COUNT * 16);

/* ------------------------------------------------------------ the faces
 *
 * Metrics come from the source art: cap line at row 2, x line at row 5,
 * baseline at row 12, descenders to row 14 of the 16-row cell.  Scaling
 * those by 0.75, 1, 1.5 and 2 gives the numbers below, so text of
 * different sizes can be sat on a common baseline by subtracting the
 * ascent -- which is exactly what a line of mixed heading and body text
 * needs.
 *
 * The italic pivot is the middle of the x-height rather than the
 * baseline, so the shear leans the glyph without also sliding it to the
 * right; ink travels about a pixel each way at 8x16 and stays inside the
 * neighbouring cells' bearings.
 */

#define FONT_VARIANTS(nm, cv, bt, W, H, ASC, CAP, XH, PIV, SM, SG, SZ)      \
    { { { nm,                cv, bt, W, H, ASC, (H) - (ASC), CAP, XH,       \
          0,  SG, PIV, 0, SZ, FONT_REGULAR, FONT_ROMAN },                   \
        { nm " italic",      cv, bt, W, H, ASC, (H) - (ASC), CAP, XH,       \
          0,  SG, PIV, 4, SZ, FONT_REGULAR, FONT_ITALIC } },                \
      { { nm " bold",        cv, bt, W, H, ASC, (H) - (ASC), CAP, XH,       \
          SM, SG, PIV, 0, SZ, FONT_BOLD, FONT_ROMAN },                      \
        { nm " bold italic", cv, bt, W, H, ASC, (H) - (ASC), CAP, XH,       \
          SM, SG, PIV, 4, SZ, FONT_BOLD, FONT_ITALIC } } }

/* The small face smears at reduced strength.  At 0.75x a stem is already
 * spread over two partly-covered columns, so a full-strength smear turns
 * every bowl into a black lozenge; bleeding a little over half of the
 * neighbouring column adds weight without closing the counters. */
static const struct font faces[FONT_SIZE_COUNT][FONT_WEIGHT_COUNT]
                             [FONT_STYLE_COUNT] = {
    FONT_VARIANTS("6x12",  gui_font_cov6x12,  0,
                  6,  12,  9,  8,  5,  6, 1, 140, FONT_SMALL),
    FONT_VARIANTS("8x16",  0, &gui_font8x16[0][0],
                  8,  16, 12, 10,  7,  8, 1, 256, FONT_BODY),
    FONT_VARIANTS("12x24", gui_font_cov12x24, 0,
                  12, 24, 18, 15, 11, 12, 1, 256, FONT_LARGE),
    FONT_VARIANTS("16x32", gui_font_cov16x32, 0,
                  16, 32, 24, 20, 14, 17, 2, 256, FONT_HUGE)
};

static int clampi(int v, int lo, int hi)
{
    if (v < lo)
        return lo;
    if (v > hi)
        return hi;
    return v;
}

const struct font *font_get(int size, int weight, int style)
{
    size = clampi(size, 0, FONT_SIZE_COUNT - 1);
    weight = clampi(weight, 0, FONT_WEIGHT_COUNT - 1);
    style = clampi(style, 0, FONT_STYLE_COUNT - 1);
    return &faces[size][weight][style];
}

const struct font *font_for_height(int px_h, int weight, int style)
{
    int best = 0;
    int i;

    /* A stylesheet can ask for any number at all; clamp before doing
     * arithmetic on it rather than after. */
    px_h = clampi(px_h, 0, 1 << 20);
    for (i = 1; i < FONT_SIZE_COUNT; i++) {
        int d = faces[i][0][0].h - px_h;
        int b = faces[best][0][0].h - px_h;

        if (d < 0)
            d = -d;
        if (b < 0)
            b = -b;
        if (d < b)
            best = i;
    }
    return font_get(best, weight, style);
}

/* ------------------------------------------------------------- metrics */

/* 0..94 for a drawable character, GLYPH_COUNT for the fallback box. */
static int glyph_index(int c)
{
    unsigned u = (unsigned)c & 0xFFu;

    if (u < GLYPH_FIRST || u > GLYPH_LAST)
        return GLYPH_COUNT;
    return (int)(u - GLYPH_FIRST);
}

int font_char_width(const struct font *f, int c)
{
    if (!f || ((unsigned)c & 0xFFu) == 0)
        return 0;
    return f->w;
}

int font_line_height(const struct font *f)
{
    return f ? f->h : 0;
}

int font_ascent(const struct font *f)
{
    return f ? f->ascent : 0;
}

int font_descent(const struct font *f)
{
    return f ? f->descent : 0;
}

/* Characters of s before the NUL, at most n (n < 0 = no limit). */
static int run_len(const char *s, int n)
{
    int i = 0;

    if (!s)
        return 0;
    while (s[i] && (n < 0 || i < n))
        i++;
    return i;
}

int font_text_width_n(const struct font *f, const char *s, int n)
{
    if (!f)
        return 0;
    return run_len(s, n) * f->w;
}

int font_text_width(const struct font *f, const char *s)
{
    return font_text_width_n(f, s, -1);
}

int font_fit(const struct font *f, const char *s, int n, int max_w,
             int *out_w)
{
    int fits;

    if (out_w)
        *out_w = 0;
    if (!f || f->w <= 0)
        return 0;
    fits = run_len(s, n);
    if (max_w >= 0) {
        int room = max_w / f->w;

        if (room < fits)
            fits = room;
    }
    if (out_w)
        *out_w = fits * f->w;
    return fits;
}

void font_measure_run(const struct font *f, const char *s, int n,
                      int max_w, int ellipsis, font_run *out)
{
    int len, room, dots;

    if (!out)
        return;
    out->width = 0;
    out->chars = 0;
    out->truncated = 0;
    out->ellipsis = 0;
    if (!f || f->w <= 0)
        return;

    len = run_len(s, n);
    if (max_w <= 0) {
        /* max_w == 0 is "no room at all"; negative is "unlimited". */
        if (max_w == 0) {
            out->truncated = len > 0;
            return;
        }
        out->chars = len;
        out->width = len * f->w;
        return;
    }

    room = max_w / f->w;
    if (room >= len) {
        out->chars = len;
        out->width = len * f->w;
        return;
    }

    out->truncated = 1;
    if (!ellipsis) {
        out->chars = room;
        out->width = room * f->w;
        return;
    }

    /* Keep room for "...", and if even that does not fit draw as many
     * dots as there is room for rather than nothing at all. */
    dots = 3;
    if (room < dots) {
        out->chars = 0;
        out->ellipsis = room;
        out->width = room * f->w;
        return;
    }
    out->chars = room - dots;
    out->ellipsis = dots;
    out->width = room * f->w;
}

/* -------------------------------------------------------------- surface */

struct target {
    uint32_t *px;
    int stride;
    int x0, y0, x1, y1;      /* clip, half-open, already inside the buffer */
};

/* Coordinates this far out cannot land on any real surface, and keeping
 * everything inside the range means none of the additions below can
 * overflow whatever a caller computed from a hostile document. */
#define FONT_COORD_MAX (1 << 24)

static int sane_coord(int v)
{
    return v > -FONT_COORD_MAX && v < FONT_COORD_MAX;
}

static int target_of(const font_surface *d, font_rc clip, struct target *t)
{
    long x1, y1;

    if (!d || !d->px || d->w <= 0 || d->h <= 0)
        return 0;
    if (!sane_coord(clip.x) || !sane_coord(clip.y) ||
        !sane_coord(clip.w) || !sane_coord(clip.h))
        return 0;
    t->px = d->px;
    t->stride = d->stride > 0 ? d->stride : d->w;
    if (t->stride < d->w)
        return 0;
    t->x0 = clip.x < 0 ? 0 : clip.x;
    t->y0 = clip.y < 0 ? 0 : clip.y;
    x1 = (long)clip.x + (clip.w > 0 ? clip.w : 0);
    y1 = (long)clip.y + (clip.h > 0 ? clip.h : 0);
    if (x1 > d->w)
        x1 = d->w;
    if (y1 > d->h)
        y1 = d->h;
    t->x1 = (int)x1;
    t->y1 = (int)y1;
    return t->x1 > t->x0 && t->y1 > t->y0;
}

/* round(v / 255) for v in 0..65025, without a divide. */
static unsigned div255(unsigned v)
{
    return ((v + 128u) * 257u) >> 16;
}

uint32_t font_blend(uint32_t bg, uint32_t fg, unsigned a)
{
    unsigned r, g, b, ia;

    if (a >= 255)
        return fg & 0xFFFFFFu;
    if (a == 0)
        return bg & 0xFFFFFFu;
    ia = 255u - a;
    r = div255(((fg >> 16) & 0xFFu) * a + ((bg >> 16) & 0xFFu) * ia);
    g = div255(((fg >> 8) & 0xFFu) * a + ((bg >> 8) & 0xFFu) * ia);
    b = div255((fg & 0xFFu) * a + (bg & 0xFFu) * ia);
    return (r << 16) | (g << 8) | b;
}

static void fill(const struct target *t, int x, int y, int w, int h,
                 uint32_t color)
{
    int px, py, xa, xb;

    xa = x < t->x0 ? t->x0 : x;
    xb = x + w > t->x1 ? t->x1 : x + w;
    for (py = y < t->y0 ? t->y0 : y; py < y + h && py < t->y1; py++) {
        uint32_t *row = t->px + (long)py * t->stride;

        for (px = xa; px < xb; px++)
            row[px] = color;
    }
}

/* ---------------------------------------------------------- rasterising */

/* Coverage 0..255 of one source pixel of one glyph. */
static unsigned cov_at(const struct font *f, int gi, int x, int y)
{
    long i;
    unsigned b;

    if (x < 0 || y < 0 || x >= f->w || y >= f->h)
        return 0;
    if (f->bits) {
        const uint8_t *rows = gi >= GLYPH_COUNT ? gui_font8x16_fallback
                                                : f->bits + (long)gi * f->h;

        return (rows[y] & (0x80u >> x)) ? 255u : 0u;
    }
    i = (long)gi * f->w * f->h / 2 + ((long)y * f->w + x) / 2;
    b = f->cov[i];
    b = (x & 1) ? (b >> 4) : (b & 0x0Fu);
    return b * 17u;              /* 0..15 -> 0..255, 15 -> exactly 255 */
}

/* Horizontal displacement of one row under the synthetic italic shear,
 * rounded away from zero so the lean is symmetric about the pivot. */
static int shear_dx(const struct font *f, int row)
{
    int d, q;

    if (f->shear_den <= 0)
        return 0;
    d = f->shear_pivot - row;
    if (d >= 0) {
        q = (2 * d + f->shear_den) / (2 * f->shear_den);
        return q;
    }
    q = (2 * -d + f->shear_den) / (2 * f->shear_den);
    return -q;
}

/* Widest face, and the size of the one scratch row the raster needs.  A
 * fixed buffer keeps the whole module allocation-free; the check in
 * raster() means a face wider than this would simply not draw rather
 * than run off the end of it. */
#define FONT_MAX_W 16

static void raster(const struct target *t, int x, int y, int gi,
                   const struct font *f, uint32_t fg)
{
    uint8_t line[FONT_MAX_W];
    int row, col;

    if (f->w > FONT_MAX_W)
        return;
    for (row = 0; row < f->h; row++) {
        int py = y + row;
        uint32_t *dst;
        int dx, lo, hi, c0;

        if (py < t->y0 || py >= t->y1)
            continue;
        /* Solve dx + col in [x0, x1) once rather than testing every
         * pixel, so a glyph mostly outside the clip costs almost
         * nothing -- which is the common case while scrolling. */
        dx = shear_dx(f, row) + x;
        lo = t->x0 - dx;
        hi = t->x1 - dx;
        if (lo < 0)
            lo = 0;
        if (hi > f->w)
            hi = f->w;
        if (lo >= hi)
            continue;

        dst = t->px + (long)py * t->stride;
        if (f->smear <= 0) {
            for (col = lo; col < hi; col++) {
                unsigned a = cov_at(f, gi, col, row);

                if (!a)
                    continue;
                dst[dx + col] = a >= 255 ? (fg & 0xFFFFFFu)
                                         : font_blend(dst[dx + col], fg, a);
            }
            continue;
        }

        /* Synthetic bold unpacks the row once and reads its neighbours
         * out of that buffer, rather than unpacking each of them again
         * per pixel: an emboldened heading then costs about what a plain
         * one does instead of three times as much. */
        c0 = lo - f->smear;
        if (c0 < 0)
            c0 = 0;
        for (col = c0; col < hi; col++)
            line[col] = (uint8_t)cov_at(f, gi, col, row);

        for (col = hi - 1; col >= lo; col--) {
            unsigned a = line[col];
            int k, px;

            for (k = 1; k <= f->smear && col - k >= c0 && a < 255; k++) {
                unsigned s = line[col - k];

                if (f->smear_gain < 256)
                    s = s * (unsigned)f->smear_gain >> 8;
                if (s > a)
                    a = s;
            }
            if (!a)
                continue;
            px = dx + col;
            dst[px] = a >= 255 ? (fg & 0xFFFFFFu)
                               : font_blend(dst[px], fg, a);
        }
    }
}

/* --------------------------------------------------------------- output */

int font_draw_char(const font_surface *dst, font_rc clip, int x, int y,
                   int c, const struct font *f, uint32_t fg, long bg)
{
    struct target t;

    if (!f)
        return 0;
    if (((unsigned)c & 0xFFu) == 0)
        return 0;
    if (!target_of(dst, clip, &t) || !sane_coord(x) || !sane_coord(y))
        return f->w;
    if (bg >= 0)
        fill(&t, x, y, f->w, f->h, (uint32_t)bg & 0xFFFFFFu);
    raster(&t, x, y, glyph_index(c), f, fg);
    return f->w;
}

int font_draw_run(const font_surface *dst, font_rc clip, int x, int y,
                  const char *s, int n, const struct font *f,
                  uint32_t fg, long bg, int max_w, int ellipsis,
                  font_run *out)
{
    font_run r;
    struct target t;
    int i, cx;

    font_measure_run(f, s, n, max_w, ellipsis, &r);
    if (out)
        *out = r;
    if (!f || r.width <= 0)
        return r.width;
    if (!target_of(dst, clip, &t) || !sane_coord(x) || !sane_coord(y))
        return r.width;

    /* The background goes down for the whole run in one pass: italic ink
     * leans out of its own cell, so filling cell by cell would let each
     * glyph erase the overhang of the one before it. */
    if (bg >= 0)
        fill(&t, x, y, r.width, f->h, (uint32_t)bg & 0xFFFFFFu);

    cx = x;
    for (i = 0; i < r.chars; i++) {
        raster(&t, cx, y, glyph_index((unsigned char)s[i]), f, fg);
        cx += f->w;
    }
    for (i = 0; i < r.ellipsis; i++) {
        raster(&t, cx, y, glyph_index('.'), f, fg);
        cx += f->w;
    }
    return r.width;
}

int font_draw_text_n(const font_surface *dst, font_rc clip, int x, int y,
                     const char *s, int n, const struct font *f,
                     uint32_t fg, long bg)
{
    return font_draw_run(dst, clip, x, y, s, n, f, fg, bg, -1, 0, 0);
}

int font_draw_text(const font_surface *dst, font_rc clip, int x, int y,
                   const char *s, const struct font *f, uint32_t fg,
                   long bg)
{
    return font_draw_run(dst, clip, x, y, s, -1, f, fg, bg, -1, 0, 0);
}
