#pragma once

/* libgui - the KestrelOS userspace GUI toolkit.
 *
 * A window is a rectangle of 32-bit 0x00RRGGBB pixels that the kernel
 * compositor maps into this process (see SYS_WIN_* in abi/kestrel_abi.h).
 * Drawing is a plain memory write into that buffer; gui_flush() publishes
 * it. Nothing here talks to the compositor except gui.c, so an app only
 * ever sees gui_* calls and struct k_event.
 *
 * Layers:
 *   gui.c       windows, the event loop, syscall wrappers, small helpers
 *   draw.c      clipped drawing primitives, text, the colour arithmetic
 *   widgets.c   buttons, labels, text boxes, lists, menus, scrollbars
 *   font_data.c the 8x16 face, generated by libgui/mkfont_user.py
 *
 * Every drawing call clips to the window and to the current clip
 * rectangle, so passing out-of-range coordinates is safe, never fatal.
 */

#include <stdint.h>
#include <kestrel.h>

/* ---------------------------------------------------------------- font */

#define GUI_FONT_W 8
#define GUI_FONT_H 16

extern const uint8_t gui_font8x16[95][16];   /* ASCII 0x20..0x7E */
extern const uint8_t gui_font8x16_fallback[16];

/* Row bitmap for one character; bit 7 is the leftmost pixel. */
const uint8_t *gui_glyph(unsigned char c);

/* -------------------------------------------------------------- colours */

#define GUI_RGB(r, g, b) \
    (((uint32_t)(r) << 16) | ((uint32_t)(g) << 8) | (uint32_t)(b))
#define GUI_RED(c)   (((c) >> 16) & 0xFF)
#define GUI_GREEN(c) (((c) >> 8) & 0xFF)
#define GUI_BLUE(c)  ((c) & 0xFF)

/* The palette is process-local but live: gui_next_event() polls
 * /etc/desktop.conf, so open applications adopt an appearance change without
 * restarting. Macros preserve the original call-site API. */
typedef struct gui_theme {
    uint32_t desk_top, desk_bottom;
    uint32_t panel, panel_hi;
    uint32_t surface, surface_alt, sunken;
    uint32_t border, edge;
    uint32_t text, text_dim, text_inv;
    uint32_t accent, accent_dark;
    uint32_t ok, warn, error, white, black;
} gui_theme;

typedef struct gui_settings {
    int light;       /* 0 = dark, 1 = light */
    int accent;      /* 0..5 */
    int wallpaper;   /* 0..3 */
    int compact;     /* compact dock */
} gui_settings;

const gui_theme *gui_theme_current(void);
void gui_settings_get(gui_settings *out);
int gui_settings_save(const gui_settings *settings);
void gui_settings_reload(void);

#define GUI_DESK_TOP     (gui_theme_current()->desk_top)
#define GUI_DESK_BOTTOM  (gui_theme_current()->desk_bottom)
#define GUI_PANEL        (gui_theme_current()->panel)
#define GUI_PANEL_HI     (gui_theme_current()->panel_hi)
#define GUI_SURFACE      (gui_theme_current()->surface)
#define GUI_SURFACE_ALT  (gui_theme_current()->surface_alt)
#define GUI_SUNKEN       (gui_theme_current()->sunken)
#define GUI_BORDER       (gui_theme_current()->border)
#define GUI_EDGE         (gui_theme_current()->edge)
#define GUI_TEXT         (gui_theme_current()->text)
#define GUI_TEXT_DIM     (gui_theme_current()->text_dim)
#define GUI_TEXT_INV     (gui_theme_current()->text_inv)
#define GUI_ACCENT       (gui_theme_current()->accent)
#define GUI_ACCENT_DARK  (gui_theme_current()->accent_dark)
#define GUI_OK           (gui_theme_current()->ok)
#define GUI_WARN         (gui_theme_current()->warn)
#define GUI_ERROR        (gui_theme_current()->error)
#define GUI_WHITE        (gui_theme_current()->white)
#define GUI_BLACK        (gui_theme_current()->black)

/* bg argument to the text calls: >= 0 is a colour, this is "leave the
 * pixels behind the glyph alone". */
#define GUI_TRANSPARENT (-1L)

/* --------------------------------------------------------------- window */

typedef struct gui_rc {
    int x, y, w, h;
} gui_rc;

typedef struct gui_window {
    uint32_t wid;        /* compositor window id                    */
    int w, h;            /* client size actually granted            */
    uint32_t *px;        /* w*h pixels, tightly packed, row-major   */
    int open;            /* 0 once closed or the compositor is gone */
    gui_rc clip;         /* current clip rectangle, window coords   */
} gui_window;

static inline gui_rc gui_mkrc(int x, int y, int w, int h)
{
    gui_rc r;

    r.x = x;
    r.y = y;
    r.w = w;
    r.h = h;
    return r;
}

/* Screen geometry. Returns 0 and fills the outputs, or -1 when the machine
 * booted without a linear framebuffer (in which case gui_open always
 * fails and an app should print an error and exit rather than spin). */
int gui_screen(int *w, int *h);

/* Create a window. flags is 0 or a mix of K_WIN_NODECOR/K_WIN_DESKTOP.
 * Returns NULL if there is no framebuffer, no compositor, or no room. */
gui_window *gui_open(const char *title, int x, int y, int w, int h,
                     unsigned flags);
void gui_close(gui_window *win);

/* Publish the pixel buffer. Returns 0, or -1 if the window is gone
 * (which also clears win->open, so event loops fall out). */
int gui_flush(gui_window *win);
int gui_move(gui_window *win, int x, int y);
int gui_window_list(int index, struct k_winsummary *out);
int gui_window_control(uint32_t wid, int action);

/* Wait up to timeout_ms for an event: 1 = *ev filled, 0 = timed out,
 * -1 = the window/compositor is gone (win->open is cleared). A timeout
 * of 0 polls. */
int gui_next_event(gui_window *win, struct k_event *ev, int timeout_ms);

/* Simple event loop. `fn` is called for every event and, when tick_ms is
 * positive, once per idle tick with an event of type KEV_NONE; returning
 * non-zero from it stops the loop. KEV_CLOSE is delivered to the handler
 * first and then always stops the loop. Returns the handler's last value,
 * or -1 if the window died under it. */
typedef int (*gui_handler)(gui_window *win, const struct k_event *ev,
                           void *ctx);
int gui_run(gui_window *win, gui_handler fn, void *ctx, int tick_ms);

/* ------------------------------------------------------ small utilities
 *
 * libc has no wrappers for these yet and libgui is not allowed to grow
 * libc, so they live here; they are the calls every GUI program needs.
 */

unsigned long gui_time(void);          /* SYS_TIME, Unix seconds */
int gui_uid(void);                     /* SYS_GETUID */
int gui_kill(int pid);                 /* SYS_KILL */
int gui_mouse(struct k_mouse *out);    /* SYS_MOUSE, screen coords */

struct gui_tm {
    int year;      /* full year, e.g. 2026 */
    int mon;       /* 1..12 */
    int day;       /* 1..31 */
    int hour, min, sec;
    int wday;      /* 0 = Sunday */
    int yday;      /* 0..365 */
};

/* Break a Unix timestamp into UTC calendar fields (proleptic Gregorian,
 * no leap seconds - the same model SYS_TIME uses). */
void gui_gmtime(unsigned long secs, struct gui_tm *tm);
const char *gui_month_name(int mon);   /* 1..12 -> "Jan".. */
const char *gui_day_name(int wday);    /* 0..6  -> "Sun".. */

/* ---------------------------------------------------- drawing (draw.c) */

/* Restrict drawing to r (intersected with the window); gui_unclip drops
 * the restriction. Clip state is per window and not stacked - save it by
 * copying win->clip if a caller needs to nest. */
void gui_clip(gui_window *win, gui_rc r);
void gui_unclip(gui_window *win);

void gui_clear(gui_window *win, uint32_t color);
void gui_pixel(gui_window *win, int x, int y, uint32_t color);
uint32_t gui_peek(gui_window *win, int x, int y);   /* 0 outside */
void gui_rect(gui_window *win, int x, int y, int w, int h, uint32_t color);
void gui_frame(gui_window *win, int x, int y, int w, int h, uint32_t color);
/* Two-tone bevel: `hi` along the top/left edges, `lo` along bottom/right. */
void gui_bevel(gui_window *win, gui_rc r, uint32_t hi, uint32_t lo);
void gui_line(gui_window *win, int x0, int y0, int x1, int y1,
              uint32_t color);
void gui_line_w(gui_window *win, int x0, int y0, int x1, int y1,
                uint32_t color, int width);
void gui_circle(gui_window *win, int cx, int cy, int r, uint32_t color);
void gui_disc(gui_window *win, int cx, int cy, int r, uint32_t color);
void gui_vgradient(gui_window *win, gui_rc r, uint32_t top, uint32_t bottom);
void gui_hgradient(gui_window *win, gui_rc r, uint32_t left, uint32_t right);
void gui_round_rect(gui_window *win, gui_rc r, int radius, uint32_t color);
void gui_round_frame(gui_window *win, gui_rc r, int radius, uint32_t color);
void gui_shadow(gui_window *win, gui_rc r, int radius, uint32_t color);

enum gui_icon {
    GUI_ICON_APPS,
    GUI_ICON_TERMINAL,
    GUI_ICON_FILES,
    GUI_ICON_BROWSER,
    GUI_ICON_PAINT,
    GUI_ICON_CLOCK,
    GUI_ICON_SETTINGS,
    GUI_ICON_INFO,
    GUI_ICON_CALCULATOR,
    GUI_ICON_MONITOR,
    GUI_ICON_NETWORK,
    GUI_ICON_POWER,
    GUI_ICON_SEARCH,
    GUI_ICON_HOME,
    GUI_ICON_CLOSE,
    GUI_ICON_CHECK
};

/* Small line icons used by the desktop and applications. The drawing stays
 * crisp at 16..32 pixels and has no image-file dependency. */
void gui_icon(gui_window *win, int x, int y, int size, enum gui_icon icon,
              uint32_t color);

/* Blend a into b, t = 0..256 (0 = a, 256 = b); gui_shade lightens for a
 * positive percentage and darkens for a negative one. */
uint32_t gui_mix(uint32_t a, uint32_t b, int t);
uint32_t gui_shade(uint32_t color, int pct);

/* Text. bg may be GUI_TRANSPARENT. All return the x coordinate just past
 * the last glyph drawn. */
int gui_char(gui_window *win, int x, int y, char c, uint32_t fg, long bg);
int gui_text(gui_window *win, int x, int y, const char *s, uint32_t fg,
             long bg);
int gui_text_n(gui_window *win, int x, int y, const char *s, int n,
               uint32_t fg, long bg);
int gui_text_w(const char *s);         /* pixel width of s */

/* Blit `src` (bw*bh pixels, `stride` pixels per row) at x,y. */
void gui_bitmap(gui_window *win, int x, int y, int bw, int bh,
                const uint32_t *src, int stride);

/* Move the clip rectangle's contents up by `rows` pixel rows and fill the
 * exposed strip at the bottom with bg. */
void gui_scroll_up(gui_window *win, int rows, uint32_t bg);

/* Fixed-point trigonometry: the angle is in tenths of a degree (3600 =
 * one turn) and the result is Q16, i.e. -65536..65536. There is no libm
 * and no FPU dependency; this is a Taylor series in 64-bit integers. */
#define GUI_TURN 3600
#define GUI_Q16  65536
int gui_sin_q16(int tenths_deg);
int gui_cos_q16(int tenths_deg);

/* ------------------------------------------------- widgets (widgets.c) */

/* Input state folded out of the event stream. Call gui_ui_begin() at the
 * top of a frame, gui_ui_event() for every event you pump, then draw the
 * widgets; they consume the one-shot fields (down/up/key). */
typedef struct gui_ui {
    int mx, my;                  /* pointer, client coordinates      */
    unsigned buttons;            /* buttons currently held           */
    int down, up;                /* a press/release happened         */
    unsigned down_btn, up_btn;   /* which buttons those carried      */
    int down_x, down_y;
    int up_x, up_y;
    int dbl;                     /* the release completed a double click */
    int key;                     /* key this frame, 0 = none         */
    int wheel;                   /* wheel steps, + = away from user  */
    unsigned long last_click_ms; /* internal: double-click timing    */
    int last_click_x, last_click_y;
} gui_ui;

void gui_ui_begin(gui_ui *ui);
void gui_ui_event(gui_ui *ui, const struct k_event *ev);
int gui_hit(gui_rc r, int x, int y);

/* A push button; returns 1 on the frame the click completes inside it. */
int gui_button(gui_window *win, gui_rc r, const char *label, gui_ui *ui);
/* enabled = 0 greys it out and never returns 1; active = 1 draws it as a
 * latched/selected button. */
int gui_button_ex(gui_window *win, gui_rc r, const char *label, gui_ui *ui,
                  int enabled, int active);
int gui_icon_button(gui_window *win, gui_rc r, enum gui_icon icon,
                    const char *label, gui_ui *ui, int enabled, int active);

void gui_label(gui_window *win, int x, int y, const char *s, uint32_t fg);

typedef struct gui_textbox_state {
    char *buf;      /* caller-owned, NUL-terminated */
    int cap;        /* bytes in buf, including the NUL */
    int len;
    int caret;
    int focus;
    int scroll;     /* first visible character */
} gui_textbox_state;

/* Single-line editable field. Returns 1 when Enter was pressed in it. */
int gui_textbox(gui_window *win, gui_rc r, gui_textbox_state *tb,
                gui_ui *ui);

typedef struct gui_list {
    int count;
    int sel;                                   /* -1 = nothing selected */
    int top;                                   /* first visible row     */
    int row_h;                                 /* 0 = GUI_FONT_H + 4    */
    const char *(*item)(void *ctx, int index); /* row text              */
    uint32_t (*tint)(void *ctx, int index);    /* optional row colour   */
    void *ctx;
} gui_list;

/* Scrollable list with selection. Returns the index the user activated
 * (double click or Enter), or -1. Single clicks and the arrow keys move
 * ls->sel. */
int gui_listbox(gui_window *win, gui_rc r, gui_list *ls, gui_ui *ui);

/* Vertical scrollbar over `total` rows of which `visible` fit. Updates
 * *top and returns 1 if it changed. */
int gui_scrollbar(gui_window *win, gui_rc r, int total, int visible,
                  int *top, gui_ui *ui);

int gui_checkbox(gui_window *win, int x, int y, const char *label, int *on,
                 gui_ui *ui);
int gui_toggle(gui_window *win, int x, int y, const char *label, int *on,
               gui_ui *ui);
void gui_card(gui_window *win, gui_rc r);
void gui_progress(gui_window *win, gui_rc r, int percent, uint32_t fill);
void gui_badge(gui_window *win, gui_rc r, const char *text, uint32_t color);

typedef struct gui_menu_state {
    int open;
    int hover;
} gui_menu_state;

/* A drop-down: `r` is the title button, the list drops below it. Returns
 * the chosen item index, or -1. Call it last in the frame so the open
 * list paints over everything else. */
int gui_menu(gui_window *win, gui_rc r, const char *title,
             const char *const *items, int n, gui_menu_state *st,
             gui_ui *ui);
