#!/usr/bin/env python3
"""Generate libgui/font_data.c -- the userspace copy of KestrelOS' 8x16 face.

Userspace cannot link against kernel/font.c (different image, different
address space), so libgui needs its own copy of the glyph bitmaps.  The
art is NOT duplicated here: this script imports tools/mkfont.py -- the
one place the typeface is designed -- calls its build() and re-emits the
same bitmaps under userspace symbol names.  Change a glyph in
tools/mkfont.py and both the kernel console and every GUI program pick
it up on the next regeneration.

Usage
-----
    python3 libgui/mkfont_user.py            # write libgui/font_data.c
    python3 libgui/mkfont_user.py --check    # verify the file is current
"""

import importlib.util
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DESIGN = os.path.join(ROOT, "tools", "mkfont.py")
OUT = os.path.join(ROOT, "libgui", "font_data.c")

BANNER = """\
/* Generated by libgui/mkfont_user.py -- do not edit by hand.
 *
 * The userspace copy of the 8x16 face designed in tools/mkfont.py; the
 * generator imports that module, so there is exactly one place where the
 * glyph art lives. Regenerate after changing the typeface:
 *
 *     python3 libgui/mkfont_user.py
 */
"""


def load_design():
    """Import tools/mkfont.py as a module without running its main()."""
    spec = importlib.util.spec_from_file_location("kestrel_mkfont", DESIGN)
    if spec is None or spec.loader is None:
        raise SystemExit(f"mkfont_user: cannot load {DESIGN}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render(mod):
    glyphs, fallback = mod.build()
    first = mod.FIRST
    lines = [BANNER.rstrip("\n"), "", '#include "gui.h"', "",
             "const uint8_t gui_font8x16[95][16] = {"]
    for i, g in enumerate(glyphs):
        ch = chr(first + i)
        shown = "\\\\" if ch == "\\" else ch
        lines.append(f"    /* 0x{first + i:02X}  '{shown}' */")
        lines.append("    { " + ", ".join(f"0x{b:02X}" for b in g) + " },")
    lines.append("};")
    lines.append("")
    lines.append("/* Drawn in place of any code point outside 0x20..0x7E. */")
    lines.append("const uint8_t gui_font8x16_fallback[16] = {")
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in fallback))
    lines.append("};")
    lines.append("")
    return "\n".join(lines), len(glyphs)


def main():
    args = sys.argv[1:]
    text, count = render(load_design())

    if args and args[0] == "--check":
        try:
            with open(OUT, "r", newline="\n") as f:
                current = f.read()
        except OSError:
            print("mkfont_user: font_data.c is missing")
            return 1
        if current != text:
            print("mkfont_user: font_data.c is stale, rerun the generator")
            return 1
        print("mkfont_user: font_data.c is up to date")
        return 0
    if args:
        print(__doc__)
        return 1

    with open(OUT, "w", newline="\n") as f:
        f.write(text)
    print(f"mkfont_user: wrote {OUT} ({count} glyphs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
