/* KestrelOS libtls: ChaCha20, Poly1305, AES, GCM and the AEAD interface.
 *
 * Written from RFC 8439, FIPS 197 and the GCM specification. Nothing is
 * copied: the AES S-box is generated at first use from the multiplicative
 * inverse in GF(2^8) followed by the published affine transform, the four
 * T-tables are generated from that S-box, the GHASH reduction table is
 * generated by repeated multiplication by x, and the per-key GHASH table
 * is generated from the reference GF(2^128) multiply below it.
 *
 * Constant-time notes, stated plainly rather than glossed:
 *   - The tag comparison in aead_ctx_open() has no early exit and no
 *     secret-dependent branch.
 *   - Poly1305 is branch-free: the final conditional subtraction of
 *     2^130 - 5 is a mask select, not an if.
 *   - ChaCha20 is naturally constant time; it has no tables at all.
 *   - AES is NOT constant time. It indexes 4 KiB of T-tables with round
 *     state derived from the key, which is observable through the data
 *     cache. GHASH's 256-byte per-key table is indexed with accumulator
 *     nibbles and has the same exposure. Fixing either needs bitslicing or
 *     hardware instructions; neither is in scope, so ChaCha20-Poly1305 is
 *     the better choice on this system and the TLS layer should prefer it.
 */

#include <aead.h>
#include <string.h>

/* ---------------- little/big-endian helpers ---------------- */

static uint32_t ld32le(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) |
           ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
}

static void st32le(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)v; p[1] = (uint8_t)(v >> 8);
    p[2] = (uint8_t)(v >> 16); p[3] = (uint8_t)(v >> 24);
}

static uint32_t ld32be(const uint8_t *p)
{
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) |
           ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

static void st32be(uint8_t *p, uint32_t v)
{
    p[0] = (uint8_t)(v >> 24); p[1] = (uint8_t)(v >> 16);
    p[2] = (uint8_t)(v >> 8); p[3] = (uint8_t)v;
}

static uint64_t ld64be(const uint8_t *p)
{
    return ((uint64_t)ld32be(p) << 32) | (uint64_t)ld32be(p + 4);
}

static void st64be(uint8_t *p, uint64_t v)
{
    st32be(p, (uint32_t)(v >> 32));
    st32be(p + 4, (uint32_t)v);
}

/* ---------------- AES (FIPS 197) ---------------- */

/* GF(2^8) modulo x^8 + x^4 + x^3 + x + 1. */
static uint8_t gf8_xtime(uint8_t a)
{
    return (uint8_t)((a << 1) ^ (((a >> 7) & 1) * 0x1b));
}

static uint8_t aes_sbox[256];
static uint32_t aes_te[4][256];
static int aes_tables_ready;

/* The S-box is the multiplicative inverse in GF(2^8) -- with 0 mapped to
 * itself -- followed by the affine transform
 *   b' = b ^ rotl(b,1) ^ rotl(b,2) ^ rotl(b,3) ^ rotl(b,4) ^ 0x63.
 * The inverse comes from a log table over the generator 3, built here
 * rather than transcribed. */
static void aes_tables_init(void)
{
    uint8_t alog[256], logt[256];
    uint8_t p;
    int i;

    if (aes_tables_ready)
        return;

    p = 1;
    for (i = 0; i < 255; i++) {
        alog[i] = p;
        logt[p] = (uint8_t)i;
        p = (uint8_t)(p ^ gf8_xtime(p));   /* p *= 3 */
    }
    alog[255] = 1;
    logt[0] = 0;

    for (i = 0; i < 256; i++) {
        uint8_t inv = (i == 0) ? 0 : alog[255 - logt[i]];
        uint8_t s = inv;
        int k;

        for (k = 1; k <= 4; k++)
            s = (uint8_t)(s ^ ((inv << k) | (inv >> (8 - k))));
        aes_sbox[i] = (uint8_t)(s ^ 0x63);
    }

    /* Te0[x] = { 2*S, S, S, 3*S }; the other three are byte rotations of
     * it, which is exactly what the MixColumns matrix rows amount to. */
    for (i = 0; i < 256; i++) {
        uint8_t s = aes_sbox[i];
        uint8_t s2 = gf8_xtime(s);
        uint8_t s3 = (uint8_t)(s2 ^ s);
        uint32_t t = ((uint32_t)s2 << 24) | ((uint32_t)s << 16) |
                     ((uint32_t)s << 8) | (uint32_t)s3;

        aes_te[0][i] = t;
        aes_te[1][i] = (t >> 8) | (t << 24);
        aes_te[2][i] = (t >> 16) | (t << 16);
        aes_te[3][i] = (t >> 24) | (t << 8);
    }

    aes_tables_ready = 1;
}

static uint32_t aes_subword(uint32_t w)
{
    return ((uint32_t)aes_sbox[(w >> 24) & 0xff] << 24) |
           ((uint32_t)aes_sbox[(w >> 16) & 0xff] << 16) |
           ((uint32_t)aes_sbox[(w >> 8) & 0xff] << 8) |
           (uint32_t)aes_sbox[w & 0xff];
}

int aes_init(struct aes_ctx *c, const uint8_t *key, unsigned long keylen)
{
    int nk, nr, total, i;
    uint8_t rc = 1;

    if (keylen != 16 && keylen != 32)
        return -1;

    aes_tables_init();

    nk = (int)(keylen / 4);
    nr = nk + 6;
    total = 4 * (nr + 1);

    for (i = 0; i < nk; i++)
        c->rk[i] = ld32be(key + 4 * i);

    for (i = nk; i < total; i++) {
        uint32_t t = c->rk[i - 1];

        if (i % nk == 0) {
            t = (t << 8) | (t >> 24);          /* RotWord */
            t = aes_subword(t);
            t ^= (uint32_t)rc << 24;           /* Rcon */
            rc = gf8_xtime(rc);
        } else if (nk > 6 && i % nk == 4) {
            t = aes_subword(t);
        }
        c->rk[i] = c->rk[i - nk] ^ t;
    }

    c->nr = nr;
    return 0;
}

void aes_encrypt_block(const struct aes_ctx *c, const uint8_t in[16],
                       uint8_t out[16])
{
    const uint32_t *rk = c->rk;
    uint32_t s0, s1, s2, s3, t0, t1, t2, t3;
    int r;

    s0 = ld32be(in) ^ rk[0];
    s1 = ld32be(in + 4) ^ rk[1];
    s2 = ld32be(in + 8) ^ rk[2];
    s3 = ld32be(in + 12) ^ rk[3];
    rk += 4;

    for (r = 1; r < c->nr; r++) {
        t0 = aes_te[0][s0 >> 24] ^ aes_te[1][(s1 >> 16) & 0xff] ^
             aes_te[2][(s2 >> 8) & 0xff] ^ aes_te[3][s3 & 0xff] ^ rk[0];
        t1 = aes_te[0][s1 >> 24] ^ aes_te[1][(s2 >> 16) & 0xff] ^
             aes_te[2][(s3 >> 8) & 0xff] ^ aes_te[3][s0 & 0xff] ^ rk[1];
        t2 = aes_te[0][s2 >> 24] ^ aes_te[1][(s3 >> 16) & 0xff] ^
             aes_te[2][(s0 >> 8) & 0xff] ^ aes_te[3][s1 & 0xff] ^ rk[2];
        t3 = aes_te[0][s3 >> 24] ^ aes_te[1][(s0 >> 16) & 0xff] ^
             aes_te[2][(s1 >> 8) & 0xff] ^ aes_te[3][s2 & 0xff] ^ rk[3];
        s0 = t0; s1 = t1; s2 = t2; s3 = t3;
        rk += 4;
    }

    /* The last round drops MixColumns, so it is a plain S-box lookup. */
    t0 = ((uint32_t)aes_sbox[s0 >> 24] << 24) |
         ((uint32_t)aes_sbox[(s1 >> 16) & 0xff] << 16) |
         ((uint32_t)aes_sbox[(s2 >> 8) & 0xff] << 8) |
         (uint32_t)aes_sbox[s3 & 0xff];
    t1 = ((uint32_t)aes_sbox[s1 >> 24] << 24) |
         ((uint32_t)aes_sbox[(s2 >> 16) & 0xff] << 16) |
         ((uint32_t)aes_sbox[(s3 >> 8) & 0xff] << 8) |
         (uint32_t)aes_sbox[s0 & 0xff];
    t2 = ((uint32_t)aes_sbox[s2 >> 24] << 24) |
         ((uint32_t)aes_sbox[(s3 >> 16) & 0xff] << 16) |
         ((uint32_t)aes_sbox[(s0 >> 8) & 0xff] << 8) |
         (uint32_t)aes_sbox[s1 & 0xff];
    t3 = ((uint32_t)aes_sbox[s3 >> 24] << 24) |
         ((uint32_t)aes_sbox[(s0 >> 16) & 0xff] << 16) |
         ((uint32_t)aes_sbox[(s1 >> 8) & 0xff] << 8) |
         (uint32_t)aes_sbox[s2 & 0xff];

    st32be(out, t0 ^ rk[0]);
    st32be(out + 4, t1 ^ rk[1]);
    st32be(out + 8, t2 ^ rk[2]);
    st32be(out + 12, t3 ^ rk[3]);
}

/* ---------------- GF(2^128) for GHASH ---------------- */

/* GCM numbers bits from the most significant bit of byte 0, so the field
 * element whose only nonzero coefficient is x^0 is 0x80 followed by
 * fifteen zeros, and multiplying by x is a *right* shift of the whole
 * 128-bit big-endian value, reducing with x^128 = x^7 + x^2 + x + 1
 * (0xe1 in the top byte) whenever a one falls off the bottom. */

struct gf {
    uint64_t hi;                      /* bytes 0..7, big-endian */
    uint64_t lo;                      /* bytes 8..15 */
};

static void gf_load(struct gf *g, const uint8_t b[16])
{
    g->hi = ld64be(b);
    g->lo = ld64be(b + 8);
}

static void gf_store(uint8_t b[16], const struct gf *g)
{
    st64be(b, g->hi);
    st64be(b + 8, g->lo);
}

/* g *= x */
static void gf_mulx(struct gf *g)
{
    uint64_t lsb = g->lo & 1;

    g->lo = (g->lo >> 1) | (g->hi << 63);
    g->hi >>= 1;
    g->hi ^= 0xe100000000000000ULL & (uint64_t)(0 - lsb);
}

/* The reference multiply from the specification: 128 shift-and-add steps,
 * no tables, no secret-dependent branch. Kept for the table build and as
 * the oracle tools/test_cryptosym.c checks the fast path against. */
void ghash_mul(uint8_t z[16], const uint8_t h[16])
{
    struct gf v, r, x;
    int i;

    gf_load(&x, z);
    gf_load(&v, h);
    r.hi = 0;
    r.lo = 0;

    for (i = 0; i < 128; i++) {
        uint64_t bit = (i < 64) ? ((x.hi >> (63 - i)) & 1)
                                : ((x.lo >> (127 - i)) & 1);
        uint64_t mask = (uint64_t)(0 - bit);

        r.hi ^= v.hi & mask;
        r.lo ^= v.lo & mask;
        gf_mulx(&v);
    }

    gf_store(z, &r);
}

/* Build the per-key table: htab[n] = H * n, where n's four bits are the
 * coefficients of x^0..x^3. htab[8] is therefore H itself. */
static void ghash_table(uint64_t htab[16][2], uint16_t rtab[16],
                        const uint8_t h[16])
{
    struct gf t[16];
    int i, j;

    t[0].hi = 0; t[0].lo = 0;
    gf_load(&t[8], h);
    t[4] = t[8]; gf_mulx(&t[4]);
    t[2] = t[4]; gf_mulx(&t[2]);
    t[1] = t[2]; gf_mulx(&t[1]);

    for (i = 2; i < 16; i *= 2)
        for (j = 1; j < i; j++) {
            t[i + j].hi = t[i].hi ^ t[j].hi;
            t[i + j].lo = t[i].lo ^ t[j].lo;
        }

    for (i = 0; i < 16; i++) {
        htab[i][0] = t[i].hi;
        htab[i][1] = t[i].lo;
    }

    /* rtab[v] is what multiplying by x^4 pushes back into the top two
     * bytes when the low nibble v falls off the bottom. Derived, not
     * transcribed: take the element that is just v in its lowest nibble
     * and multiply it by x four times. */
    for (i = 0; i < 16; i++) {
        struct gf g;
        int k;

        g.hi = 0;
        g.lo = (uint64_t)i;
        for (k = 0; k < 4; k++)
            gf_mulx(&g);
        rtab[i] = (uint16_t)(g.hi >> 48);
    }
}

/* z = z * H, four bits of z at a time, most significant nibble last:
 *   z*H = sum_k T[n_k] * x^(4k)
 * evaluated by Horner from the lowest-order nibble upward. */
static void ghash_mul_fast(struct gf *z, const uint64_t htab[16][2],
                           const uint16_t rtab[16])
{
    struct gf s;
    int k;

    s.hi = 0;
    s.lo = 0;

    for (k = 31; k >= 0; k--) {
        unsigned int n = (k < 16)
            ? (unsigned int)((z->hi >> (60 - 4 * k)) & 0xf)
            : (unsigned int)((z->lo >> (60 - 4 * (k - 16))) & 0xf);
        unsigned int v = (unsigned int)(s.lo & 0xf);

        s.lo = (s.lo >> 4) | (s.hi << 60);
        s.hi = (s.hi >> 4) ^ ((uint64_t)rtab[v] << 48);
        s.hi ^= htab[n][0];
        s.lo ^= htab[n][1];
    }

    *z = s;
}

/* Absorb whole blocks, zero-padding a short tail to 16 bytes. */
static void ghash_blocks(struct gf *y, const uint64_t htab[16][2],
                         const uint16_t rtab[16],
                         const uint8_t *data, unsigned long len)
{
    while (len) {
        uint8_t blk[16];
        unsigned long take = (len < 16) ? len : 16;

        memset(blk, 0, sizeof(blk));
        memcpy(blk, data, take);

        y->hi ^= ld64be(blk);
        y->lo ^= ld64be(blk + 8);
        ghash_mul_fast(y, htab, rtab);

        data += take;
        len -= take;
    }
}

/* ---------------- ChaCha20 (RFC 8439) ---------------- */

static uint32_t rotl32(uint32_t x, unsigned int n)
{
    return (x << n) | (x >> (32 - n));
}

#define CHACHA_QR(a, b, c, d)                       \
    do {                                            \
        a += b; d ^= a; d = rotl32(d, 16);          \
        c += d; b ^= c; b = rotl32(b, 12);          \
        a += b; d ^= a; d = rotl32(d, 8);           \
        c += d; b ^= c; b = rotl32(b, 7);           \
    } while (0)

static void chacha20_core(const uint32_t in[16], uint8_t out[64])
{
    uint32_t x[16];
    int i;

    for (i = 0; i < 16; i++)
        x[i] = in[i];

    /* Twenty rounds: ten column rounds each followed by a diagonal one. */
    for (i = 0; i < 10; i++) {
        CHACHA_QR(x[0], x[4], x[8],  x[12]);
        CHACHA_QR(x[1], x[5], x[9],  x[13]);
        CHACHA_QR(x[2], x[6], x[10], x[14]);
        CHACHA_QR(x[3], x[7], x[11], x[15]);
        CHACHA_QR(x[0], x[5], x[10], x[15]);
        CHACHA_QR(x[1], x[6], x[11], x[12]);
        CHACHA_QR(x[2], x[7], x[8],  x[13]);
        CHACHA_QR(x[3], x[4], x[9],  x[14]);
    }

    for (i = 0; i < 16; i++)
        st32le(out + 4 * i, x[i] + in[i]);
}

static void chacha20_state(uint32_t st[16], const uint8_t key[32],
                           uint32_t counter, const uint8_t nonce[12])
{
    int i;

    /* "expand 32-byte k", as four little-endian words. */
    st[0] = 0x61707865U;
    st[1] = 0x3320646eU;
    st[2] = 0x79622d32U;
    st[3] = 0x6b206574U;
    for (i = 0; i < 8; i++)
        st[4 + i] = ld32le(key + 4 * i);
    st[12] = counter;
    for (i = 0; i < 3; i++)
        st[13 + i] = ld32le(nonce + 4 * i);
}

void chacha20_block(const uint8_t key[32], uint32_t counter,
                    const uint8_t nonce[12], uint8_t out[64])
{
    uint32_t st[16];

    chacha20_state(st, key, counter, nonce);
    chacha20_core(st, out);
}

int chacha20_xor(const uint8_t key[32], uint32_t counter,
                 const uint8_t nonce[12], const uint8_t *in,
                 unsigned long len, uint8_t *out)
{
    uint32_t st[16];
    uint8_t ks[64];
    unsigned long done = 0;

    if (!len)
        return 0;

    /* The block counter is 32 bits and the spec does not wrap it. */
    {
        unsigned long blocks = (len + 63) / 64;

        if (blocks > (unsigned long)(0xffffffffUL - counter) + 1UL)
            return -1;
    }

    chacha20_state(st, key, counter, nonce);

    while (done < len) {
        unsigned long take = len - done;
        unsigned long i;

        if (take > 64)
            take = 64;
        chacha20_core(st, ks);
        for (i = 0; i < take; i++)
            out[done + i] = (uint8_t)(in[done + i] ^ ks[i]);
        done += take;
        st[12]++;
    }

    memset(ks, 0, sizeof(ks));
    memset(st, 0, sizeof(st));
    return 0;
}

/* ---------------- Poly1305 (RFC 8439) ---------------- */

/* The accumulator and the clamped key are held as five 26-bit limbs, so a
 * limb product fits a uint64 with room for the five-term sum. Reduction
 * modulo 2^130 - 5 folds the top limb back with a factor of 5. There is
 * no branch anywhere on key or message data. */

#define P1305_MASK 0x3ffffffUL

void poly1305_init(struct poly1305_ctx *c, const uint8_t key[32])
{
    uint8_t rk[16];

    memcpy(rk, key, 16);
    /* r &= 0x0ffffffc0ffffffc0ffffffc0fffffff */
    rk[3] &= 15; rk[7] &= 15; rk[11] &= 15; rk[15] &= 15;
    rk[4] &= 252; rk[8] &= 252; rk[12] &= 252;

    c->r[0] = ld32le(rk) & P1305_MASK;
    c->r[1] = (ld32le(rk + 3) >> 2) & P1305_MASK;
    c->r[2] = (ld32le(rk + 6) >> 4) & P1305_MASK;
    c->r[3] = (ld32le(rk + 9) >> 6) & P1305_MASK;
    c->r[4] = (ld32le(rk + 12) >> 8) & P1305_MASK;

    c->h[0] = c->h[1] = c->h[2] = c->h[3] = c->h[4] = 0;

    c->pad[0] = ld32le(key + 16);
    c->pad[1] = ld32le(key + 20);
    c->pad[2] = ld32le(key + 24);
    c->pad[3] = ld32le(key + 28);

    c->buflen = 0;
    memset(c->buf, 0, sizeof(c->buf));
    memset(rk, 0, sizeof(rk));
}

/* hibit is 1<<24 for a full block, 0 for the final short one (whose 0x01
 * terminator the caller has already placed in the padded buffer). */
static void poly1305_blocks(struct poly1305_ctx *c, const uint8_t *m,
                            unsigned long bytes, uint32_t hibit)
{
    uint32_t r0 = c->r[0], r1 = c->r[1], r2 = c->r[2];
    uint32_t r3 = c->r[3], r4 = c->r[4];
    uint32_t s1 = r1 * 5, s2 = r2 * 5, s3 = r3 * 5, s4 = r4 * 5;
    uint32_t h0 = c->h[0], h1 = c->h[1], h2 = c->h[2];
    uint32_t h3 = c->h[3], h4 = c->h[4];

    while (bytes >= 16) {
        uint64_t d0, d1, d2, d3, d4, carry;

        h0 += ld32le(m) & P1305_MASK;
        h1 += (ld32le(m + 3) >> 2) & P1305_MASK;
        h2 += (ld32le(m + 6) >> 4) & P1305_MASK;
        h3 += (ld32le(m + 9) >> 6) & P1305_MASK;
        h4 += (ld32le(m + 12) >> 8) | hibit;

        d0 = (uint64_t)h0 * r0 + (uint64_t)h1 * s4 + (uint64_t)h2 * s3 +
             (uint64_t)h3 * s2 + (uint64_t)h4 * s1;
        d1 = (uint64_t)h0 * r1 + (uint64_t)h1 * r0 + (uint64_t)h2 * s4 +
             (uint64_t)h3 * s3 + (uint64_t)h4 * s2;
        d2 = (uint64_t)h0 * r2 + (uint64_t)h1 * r1 + (uint64_t)h2 * r0 +
             (uint64_t)h3 * s4 + (uint64_t)h4 * s3;
        d3 = (uint64_t)h0 * r3 + (uint64_t)h1 * r2 + (uint64_t)h2 * r1 +
             (uint64_t)h3 * r0 + (uint64_t)h4 * s4;
        d4 = (uint64_t)h0 * r4 + (uint64_t)h1 * r3 + (uint64_t)h2 * r2 +
             (uint64_t)h3 * r1 + (uint64_t)h4 * r0;

        carry = d0 >> 26; h0 = (uint32_t)d0 & P1305_MASK;
        d1 += carry; carry = d1 >> 26; h1 = (uint32_t)d1 & P1305_MASK;
        d2 += carry; carry = d2 >> 26; h2 = (uint32_t)d2 & P1305_MASK;
        d3 += carry; carry = d3 >> 26; h3 = (uint32_t)d3 & P1305_MASK;
        d4 += carry; carry = d4 >> 26; h4 = (uint32_t)d4 & P1305_MASK;
        h0 += (uint32_t)carry * 5;
        carry = h0 >> 26; h0 &= P1305_MASK;
        h1 += (uint32_t)carry;

        m += 16;
        bytes -= 16;
    }

    c->h[0] = h0; c->h[1] = h1; c->h[2] = h2; c->h[3] = h3; c->h[4] = h4;
}

void poly1305_update(struct poly1305_ctx *c, const void *data,
                     unsigned long len)
{
    const uint8_t *p = (const uint8_t *)data;

    if (c->buflen) {
        unsigned long need = 16 - c->buflen;

        if (len < need) {
            memcpy(c->buf + c->buflen, p, len);
            c->buflen += len;
            return;
        }
        memcpy(c->buf + c->buflen, p, need);
        poly1305_blocks(c, c->buf, 16, 1UL << 24);
        c->buflen = 0;
        p += need;
        len -= need;
    }

    if (len >= 16) {
        unsigned long whole = len & ~15UL;

        poly1305_blocks(c, p, whole, 1UL << 24);
        p += whole;
        len -= whole;
    }

    if (len) {
        memcpy(c->buf, p, len);
        c->buflen = len;
    }
}

void poly1305_final(struct poly1305_ctx *c, uint8_t tag[16])
{
    uint32_t h0, h1, h2, h3, h4;
    uint32_t g0, g1, g2, g3, g4, mask, carry;
    uint32_t limb[5];
    uint8_t raw[16];
    uint64_t acc, f;
    unsigned int nbits;
    int li, i;

    if (c->buflen) {
        unsigned long n = c->buflen;

        c->buf[n++] = 1;
        while (n < 16)
            c->buf[n++] = 0;
        poly1305_blocks(c, c->buf, 16, 0);
    }

    h0 = c->h[0]; h1 = c->h[1]; h2 = c->h[2]; h3 = c->h[3]; h4 = c->h[4];

    carry = h1 >> 26; h1 &= P1305_MASK;
    h2 += carry; carry = h2 >> 26; h2 &= P1305_MASK;
    h3 += carry; carry = h3 >> 26; h3 &= P1305_MASK;
    h4 += carry; carry = h4 >> 26; h4 &= P1305_MASK;
    h0 += carry * 5; carry = h0 >> 26; h0 &= P1305_MASK;
    h1 += carry;

    /* g = h + 5. If that did not borrow out of the top limb, h was at
     * least 2^130 - 5 and g is the reduced value. Selected by mask, so
     * the branch never depends on the accumulator. */
    g0 = h0 + 5; carry = g0 >> 26; g0 &= P1305_MASK;
    g1 = h1 + carry; carry = g1 >> 26; g1 &= P1305_MASK;
    g2 = h2 + carry; carry = g2 >> 26; g2 &= P1305_MASK;
    g3 = h3 + carry; carry = g3 >> 26; g3 &= P1305_MASK;
    g4 = h4 + carry - (1UL << 26);

    mask = (g4 >> 31) - 1;            /* 0 if it borrowed, all ones if not */
    h0 = (h0 & ~mask) | (g0 & mask);
    h1 = (h1 & ~mask) | (g1 & mask);
    h2 = (h2 & ~mask) | (g2 & mask);
    h3 = (h3 & ~mask) | (g3 & mask);
    h4 = (h4 & ~mask) | (g4 & mask);

    /* Serialise the limbs little-endian.
     *
     * The usual repack here is a shift-and-OR, which is correct only
     * because no limb can leave the chain above holding exactly 2^26: the
     * final `h1 += carry` could in principle produce that, but the carry
     * it adds can only be nonzero when h4 overflowed, and h4 can only
     * overflow when h1 entered the chain saturated -- which is precisely
     * the case that masks h1 to zero first. The two preconditions exclude
     * each other, so the OR never overlaps.
     *
     * That is a real invariant but a fragile thing to depend on, and it
     * would break silently rather than loudly. Accumulating with addition
     * instead is correct for any limb values at all, and it runs once per
     * MAC rather than once per block, so it costs nothing measurable. */
    limb[0] = h0; limb[1] = h1; limb[2] = h2; limb[3] = h3; limb[4] = h4;
    acc = 0;
    nbits = 0;
    li = 0;
    for (i = 0; i < 16; i++) {
        while (nbits < 8 && li < 5) {
            acc += (uint64_t)limb[li] << nbits;
            nbits += 26;
            li++;
        }
        raw[i] = (uint8_t)acc;
        acc >>= 8;
        nbits -= 8;
    }

    /* tag = (accumulator + s) mod 2^128 */
    f = (uint64_t)ld32le(raw) + c->pad[0];
    st32le(tag, (uint32_t)f);
    f = (uint64_t)ld32le(raw + 4) + c->pad[1] + (f >> 32);
    st32le(tag + 4, (uint32_t)f);
    f = (uint64_t)ld32le(raw + 8) + c->pad[2] + (f >> 32);
    st32le(tag + 8, (uint32_t)f);
    f = (uint64_t)ld32le(raw + 12) + c->pad[3] + (f >> 32);
    st32le(tag + 12, (uint32_t)f);

    memset(raw, 0, sizeof(raw));
    memset(limb, 0, sizeof(limb));

    memset(c, 0, sizeof(*c));
}

void poly1305_mac(const uint8_t key[32], const void *data, unsigned long len,
                  uint8_t tag[16])
{
    struct poly1305_ctx c;

    poly1305_init(&c, key);
    poly1305_update(&c, data, len);
    poly1305_final(&c, tag);
}

/* ---------------- AEAD: properties ---------------- */

unsigned long aead_key_len(int alg)
{
    switch (alg) {
    case AEAD_CHACHA20_POLY1305: return 32;
    case AEAD_AES_128_GCM:       return 16;
    case AEAD_AES_256_GCM:       return 32;
    default:                     return 0;
    }
}

unsigned long aead_nonce_len(int alg)
{
    return aead_key_len(alg) ? AEAD_NONCE_LEN : 0;
}

unsigned long aead_tag_len(int alg)
{
    return aead_key_len(alg) ? AEAD_TAG_LEN : 0;
}

const char *aead_name(int alg)
{
    switch (alg) {
    case AEAD_CHACHA20_POLY1305: return "CHACHA20-POLY1305";
    case AEAD_AES_128_GCM:       return "AES-128-GCM";
    case AEAD_AES_256_GCM:       return "AES-256-GCM";
    default:                     return "?";
    }
}

int aead_init(struct aead_ctx *c, int alg, const uint8_t *key)
{
    unsigned long klen = aead_key_len(alg);

    if (!klen || !key)
        return -1;

    memset(c, 0, sizeof(*c));
    c->alg = alg;

    if (alg == AEAD_CHACHA20_POLY1305) {
        memcpy(c->key, key, klen);
    } else {
        uint8_t h[16];
        uint8_t zero[16];

        if (aes_init(&c->aes, key, klen) < 0)
            return -1;
        /* H = E_K(0^128) */
        memset(zero, 0, sizeof(zero));
        aes_encrypt_block(&c->aes, zero, h);
        ghash_table(c->htab, c->rtab, h);
        memset(h, 0, sizeof(h));
    }
    return 0;
}

/* ---------------- constant-time tag comparison ---------------- */

/* Returns 0 if the two buffers are equal and nonzero otherwise, having
 * touched every byte either way. The caller branches on the result, which
 * is the accept/reject decision and therefore already public. */
static uint8_t ct_diff(const uint8_t *a, const uint8_t *b, unsigned long n)
{
    uint8_t d = 0;
    unsigned long i;

    for (i = 0; i < n; i++)
        d = (uint8_t)(d | (a[i] ^ b[i]));
    return d;
}

/* ---------------- ChaCha20-Poly1305 (RFC 8439 section 2.8) ---------------- */

static void cp_pad16(struct poly1305_ctx *p, unsigned long len)
{
    static const uint8_t zeros[16] = { 0 };
    unsigned long rem = len % 16;

    if (rem)
        poly1305_update(p, zeros, 16 - rem);
}

static void cp_tag(const uint8_t key[32], const uint8_t *nonce,
                   const uint8_t *aad, unsigned long aadlen,
                   const uint8_t *ct, unsigned long ctlen, uint8_t tag[16])
{
    uint8_t block[64];
    uint8_t lens[16];
    struct poly1305_ctx p;

    /* The one-time Poly1305 key is the first 32 bytes of block 0. */
    chacha20_block(key, 0, nonce, block);
    poly1305_init(&p, block);
    memset(block, 0, sizeof(block));

    if (aadlen)
        poly1305_update(&p, aad, aadlen);
    cp_pad16(&p, aadlen);
    if (ctlen)
        poly1305_update(&p, ct, ctlen);
    cp_pad16(&p, ctlen);

    /* The two lengths, little-endian, 64 bits each. */
    st32le(lens, (uint32_t)aadlen);
    st32le(lens + 4, (uint32_t)((uint64_t)aadlen >> 32));
    st32le(lens + 8, (uint32_t)ctlen);
    st32le(lens + 12, (uint32_t)((uint64_t)ctlen >> 32));
    poly1305_update(&p, lens, 16);

    poly1305_final(&p, tag);
}

/* ---------------- AES-GCM ---------------- */

/* GCTR over `len` bytes starting from counter block `ctr`, which this
 * advances. */
static void gcm_ctr(const struct aes_ctx *aes, uint8_t ctr[16],
                    const uint8_t *in, unsigned long len, uint8_t *out)
{
    unsigned long done = 0;

    while (done < len) {
        uint8_t ks[16];
        unsigned long take = len - done;
        unsigned long i;
        uint32_t n;

        if (take > 16)
            take = 16;

        /* inc32: only the rightmost 32 bits of the counter block move. */
        n = ld32be(ctr + 12) + 1;
        st32be(ctr + 12, n);

        aes_encrypt_block(aes, ctr, ks);
        for (i = 0; i < take; i++)
            out[done + i] = (uint8_t)(in[done + i] ^ ks[i]);
        done += take;
        memset(ks, 0, sizeof(ks));
    }
}

static void gcm_tag(const struct aead_ctx *c, const uint8_t *nonce,
                    const uint8_t *aad, unsigned long aadlen,
                    const uint8_t *ct, unsigned long ctlen, uint8_t tag[16])
{
    struct gf y;
    uint8_t j0[16], lens[16], s[16], ek[16];
    unsigned long i;

    /* A 96-bit IV gives J0 = IV || 0^31 || 1 directly. */
    memcpy(j0, nonce, 12);
    st32be(j0 + 12, 1);

    y.hi = 0;
    y.lo = 0;
    ghash_blocks(&y, c->htab, c->rtab, aad, aadlen);
    ghash_blocks(&y, c->htab, c->rtab, ct, ctlen);

    st64be(lens, (uint64_t)aadlen * 8);
    st64be(lens + 8, (uint64_t)ctlen * 8);
    ghash_blocks(&y, c->htab, c->rtab, lens, 16);

    gf_store(s, &y);
    aes_encrypt_block(&c->aes, j0, ek);
    for (i = 0; i < 16; i++)
        tag[i] = (uint8_t)(s[i] ^ ek[i]);

    memset(ek, 0, sizeof(ek));
}

/* ---------------- AEAD: seal and open ---------------- */

static int aead_lens_ok(unsigned long aadlen, unsigned long len)
{
    return aadlen <= AEAD_MAX_AAD && len <= AEAD_MAX_PLAINTEXT;
}

int aead_ctx_seal(const struct aead_ctx *c, const uint8_t *nonce,
                  const uint8_t *aad, unsigned long aadlen,
                  const uint8_t *plain, unsigned long plainlen,
                  uint8_t *out)
{
    if (!aead_key_len(c->alg) || !nonce || !out)
        return -1;
    if (!aead_lens_ok(aadlen, plainlen))
        return -1;

    if (c->alg == AEAD_CHACHA20_POLY1305) {
        /* Block 0 is spent on the Poly1305 key, so the payload starts at
         * block 1. */
        if (plainlen && chacha20_xor(c->key, 1, nonce, plain, plainlen, out) < 0)
            return -1;
        cp_tag(c->key, nonce, aad, aadlen, out, plainlen, out + plainlen);
    } else {
        uint8_t ctr[16];

        memcpy(ctr, nonce, 12);
        st32be(ctr + 12, 1);
        if (plainlen)
            gcm_ctr(&c->aes, ctr, plain, plainlen, out);
        gcm_tag(c, nonce, aad, aadlen, out, plainlen, out + plainlen);
        memset(ctr, 0, sizeof(ctr));
    }
    return 0;
}

int aead_ctx_open(const struct aead_ctx *c, const uint8_t *nonce,
                  const uint8_t *aad, unsigned long aadlen,
                  const uint8_t *ct, unsigned long ctlen,
                  uint8_t *out)
{
    uint8_t want[16];
    unsigned long plainlen;

    if (!aead_key_len(c->alg) || !nonce)
        return -1;
    if (ctlen < AEAD_TAG_LEN)
        return -1;

    plainlen = ctlen - AEAD_TAG_LEN;
    if (!aead_lens_ok(aadlen, plainlen))
        return -1;
    if (plainlen && !out)
        return -1;

    /* Both constructions authenticate the ciphertext, so the tag can be
     * checked before a single byte of plaintext exists. A forgery
     * therefore never produces output, not even transiently. */
    if (c->alg == AEAD_CHACHA20_POLY1305)
        cp_tag(c->key, nonce, aad, aadlen, ct, plainlen, want);
    else
        gcm_tag(c, nonce, aad, aadlen, ct, plainlen, want);

    if (ct_diff(want, ct + plainlen, AEAD_TAG_LEN) != 0) {
        memset(want, 0, sizeof(want));
        return -1;
    }
    memset(want, 0, sizeof(want));

    if (!plainlen)
        return 0;

    if (c->alg == AEAD_CHACHA20_POLY1305) {
        if (chacha20_xor(c->key, 1, nonce, ct, plainlen, out) < 0)
            return -1;
    } else {
        uint8_t ctr[16];

        memcpy(ctr, nonce, 12);
        st32be(ctr + 12, 1);
        gcm_ctr(&c->aes, ctr, ct, plainlen, out);
        memset(ctr, 0, sizeof(ctr));
    }
    return 0;
}

int aead_seal(int alg, const uint8_t *key, const uint8_t *nonce,
              const uint8_t *aad, unsigned long aadlen,
              const uint8_t *plain, unsigned long plainlen, uint8_t *out)
{
    struct aead_ctx c;
    int r;

    if (aead_init(&c, alg, key) < 0)
        return -1;
    r = aead_ctx_seal(&c, nonce, aad, aadlen, plain, plainlen, out);
    memset(&c, 0, sizeof(c));
    return r;
}

int aead_open(int alg, const uint8_t *key, const uint8_t *nonce,
              const uint8_t *aad, unsigned long aadlen,
              const uint8_t *ct, unsigned long ctlen, uint8_t *out)
{
    struct aead_ctx c;
    int r;

    if (aead_init(&c, alg, key) < 0)
        return -1;
    r = aead_ctx_open(&c, nonce, aad, aadlen, ct, ctlen, out);
    memset(&c, 0, sizeof(c));
    return r;
}

void aead_nonce(const uint8_t *iv, unsigned long ivlen, uint64_t seq,
                uint8_t *out)
{
    unsigned long i;

    memcpy(out, iv, ivlen);
    for (i = 0; i < 8 && i < ivlen; i++)
        out[ivlen - 1 - i] ^= (uint8_t)(seq >> (8 * i));
}
