/* kernel/include/config.h - GENERATED by tools/mkconfig.py
 * from the repo-root `config` file. Do not edit: run
 * `python3 tools/mkconfig.py` instead.
 *
 * y -> #define CONFIG_X 1
 * m -> #define CONFIG_X_MODULE 1
 * n -> no #define at all, so #ifdef CONFIG_X is the test
 *      for "present in the kernel image" and
 *      #if defined(CONFIG_X) || defined(CONFIG_X_MODULE)
 *      is the test for "present at all".
 */

#ifndef KESTREL_CONFIG_H
#define KESTREL_CONFIG_H

/* Loadable kernel modules: export table, ET_REL loader, insmod/rmmod/lsmod. */
#define CONFIG_MODULES 1

/* Kernel log ring behind klog_printf, dmesg and /dev/klog. */
#define CONFIG_KLOG 1

/* /dev: null, zero, full, console, random, klog. */
#define CONFIG_DEVFS 1

/* In-kernel rescue console for a machine that cannot start /bin/init. */
#define CONFIG_KMON 1

/* RealTek RTL8139 ethernet driver (QEMU's default NIC). */
#define CONFIG_NET_RTL8139 1

/* Intel 82540EM (e1000) ethernet driver (VirtualBox's default NIC). */
#define CONFIG_NET_E1000 1

/* TCP, and the userspace that needs it: curl, wget, telnet, http:// in the browser and kpkg. */
#define CONFIG_TCP 1

/* UDP datagram sockets and the `udp` tool. */
#define CONFIG_UDP 1

/* DNS resolver and `nslookup`. */
#define CONFIG_DNS 1

/* Linear framebuffer and the graphical console backend. */
#define CONFIG_GRAPHICS 1

/* Compositor, window manager and the GUI apps. */
#define CONFIG_WM 1

/* PS/2 mouse driver. */
#define CONFIG_MOUSE 1

/* Stage the .kpkg repository into the disk image so `kpkg install` works offline. */
#define CONFIG_PACKAGES 1

/* Games: apps/snake.c. */
#define CONFIG_APPS_GAMES 1

#endif /* KESTREL_CONFIG_H */
